# Cloudflare Pages Configuration

name = "ai-saju-free"
compatibility_date = "2024-01-01"

[env.production]
name = "ai-saju-free"

[env.production.vars]
ENVIRONMENT = "production"

# Functions configuration
[[env.production.services]]
service = "ai-analysis"
environment = "production"
