# Cloudflare Pages Configuration

name = "ai-saju-free"
compatibility_date = "2024-01-01"

[env.production]
name = "ai-saju-free"

[env.production.vars]
ENVIRONMENT = "production"
# GEMINI_API_KEY는 Cloudflare Pages 대시보드에서 환경 변수로 설정해야 합니다.
# 보안상 이 파일에 직접 입력하지 마세요.

# Functions configuration
[[env.production.services]]
service = "ai-analysis"
environment = "production"
